server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-product
  application:
    name: seata-product

seata:
  service:
    vgroup-mapping:
      seata-product: default
    grouplist:
      default: 127.0.0.1:8091

logging:
  level:
    com.example.seataproduct.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml