server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-order
  application:
    name: seata-order

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  service:
    vgroup-mapping:
      seata-order: default
    grouplist:
      default: 127.0.0.1:8091